name: coffee_shop
version: 0.0.1
author: James Hurford <terrasea@gmail.com>
description: Coffee Shop using DI and Flyweight design patterns
#homepage: https://github.com/nzgreens/candidate_card.git
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  polymer: ">=1.0.0-rc.2 <2.0.0"
  polymer_interop: ">=1.0.0-rc.1 <2.0.0"
  web_components: ">=0.12.0+3 <0.13.0"
  reflectable: '>=0.4.0 <0.5.0'
  polymer_elements: ">=1.0.0-rc.2 < 2.0.0"
  browser: any
dev_dependencies:
  test: any
transformers:
- web_components:
    entry_points:
    - test/index.html
    - web/index.html
- reflectable:
    entry_points:
    - test/test.dart
    - web/main.dart
- test/pub_serve:
    $include: test/test.dart
- $dart2js:
    minify: false